### ISSUE TITLE
simSetJointTargetVelocity question

### ISSUE THREAD

**Issue by liyaozone** [gentaiscool/ros-vrep-slam#2]
Hello, I'm a beginner in vrep software. I refer to this package to build my scene, which part of the code is not very clear. 

```
-- set velocity
function velocity_callback(msg)
    -- This is the sub_velocity callback function
    -- simAddStatusbarMessage('sub_velocity receiver: ' .. msg.linear.x)
    simAuxiliaryConsolePrint(console_debug,'linear: ' .. msg.linear.x)
    simAuxiliaryConsolePrint(console_debug,' angular: ' .. msg.angular.z)
    vLeft = 6*msg.linear.x - 0.6*msg.angular.z
    vRight = 6*msg.linear.x + 0.6*msg.angular.z
    simSetJointTargetVelocity(motorLeft,vLeft)
    simSetJointTargetVelocity(motorRight,vRight)
end
```

I don't know these two formulas. 
```
    vLeft = 6*msg.linear.x - 0.6*msg.angular.z
    vRight = 6*msg.linear.x + 0.6*msg.angular.z
```
can you solve it, please. Thanks a lot.

**Comment by gentaiscool** [comment]
vLeft and vRight should be the variable for measuring the velocity of each motor. I think you can decide the direction of the object movement by testing with some numbers.

**Comment by liyaozone** [comment]
ok, thank you very much. I have solved it by this way:
```
    v_left  = (1.0/wheel_radius)*(msg.linear.x - axes_length/2.0*msg.angular.z) 
    v_right = (1.0/wheel_radius)*(msg.linear.x + axes_length/2.0*msg.angular.z)
```
And I built the robot model and scene by your project env.ttt. Can you tell me how to calculate odom pose and twist? I find that many people get their odom location through the floor. How did you do it?
